version: "3.7"
services: 
  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - '5432:5432'

  addressbook:
    image: $DOCKER_USERNAME/dockerizing-modejs-addressbook:latest
    command: "npm run migrate && npm run pm2"
    environment: 
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on: 
    - postgres
    ports: 
    - '3000:3000'